// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2181.PracticeBot2018;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;
import edu.wpi.first.wpilibj.RobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX driveTrainTalonSRX1;
    public static WPI_TalonSRX driveTrainTalonSRX2;
    public static WPI_TalonSRX driveTrainTalonSRX3;
    public static WPI_TalonSRX driveTrainTalonSRX4;
    public static RobotDrive driveTrainRobotDrive41;
    public static WPI_TalonSRX ropeSpoolTalonSRX5;
    public static WPI_TalonSRX ropeSpoolTalonSRX6;
    public static WPI_VictorSPX gearFlipperVictorSPX1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainTalonSRX1 = new WPI_TalonSRX(0);
        
        
        driveTrainTalonSRX2 = new WPI_TalonSRX(1);
        
        
        driveTrainTalonSRX3 = new WPI_TalonSRX(2);
        
        
        driveTrainTalonSRX4 = new WPI_TalonSRX(3);
        
        
        driveTrainRobotDrive41 = new RobotDrive(driveTrainTalonSRX2, driveTrainTalonSRX3,
              driveTrainTalonSRX1, driveTrainTalonSRX4);
        
        driveTrainRobotDrive41.setSafetyEnabled(false);
        driveTrainRobotDrive41.setExpiration(0.1);
        driveTrainRobotDrive41.setSensitivity(0.5);
        driveTrainRobotDrive41.setMaxOutput(1.0);

        driveTrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        driveTrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        ropeSpoolTalonSRX5 = new WPI_TalonSRX(4);
        
        
        ropeSpoolTalonSRX6 = new WPI_TalonSRX(5);
        
        
        gearFlipperVictorSPX1 = new WPI_VictorSPX(6);
        
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
